require('dotenv').config({ path: require('path').join(__dirname, '../.env') })
const mongoose = require('mongoose')
const bcrypt = require('bcryptjs')
const { randomUUID } = require('crypto')

const User = require('../models/User')
const Course = require('../models/Course')
const Lesson = require('../models/Lesson')
const Quiz = require('../models/Quiz')
const Enrollment = require('../models/Enrollment')
const Progress = require('../models/Progress')

const SALT_ROUNDS = 10

function pickRandom(arr, min, max) {
  const count = min + Math.floor(Math.random() * (max - min + 1))
  const shuffled = [...arr].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(count, arr.length))
}

function randomInt(min, max) {
  return min + Math.floor(Math.random() * (max - min + 1))
}

function makeSlug(title) {
  return title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-') + '-' + Date.now().toString(36)
}

const courseData = [
  {
    title: 'Algebra Foundations',
    category: 'Mathematics',
    level: 'Beginner',
    description: 'Master the fundamentals of algebra from the ground up. This course covers variables, expressions, and equations in a clear, step-by-step format. Perfect for students who want to build a solid mathematical foundation before advancing to higher-level mathematics.',
    tags: ['algebra', 'math', 'equations', 'beginner'],
    lessons: [
      { title: 'Introduction to Variables and Expressions', duration: 15, order: 1, content: `<h3>What is a Variable?</h3><p>In mathematics, a variable is a symbol—usually a letter such as x, y, or z—used to represent an unknown or changing quantity. Variables are the cornerstone of algebra, allowing us to write general rules and solve problems without knowing the exact numbers involved. For example, if you earn $10 per hour, you can write your total earnings as 10h, where h represents the number of hours worked. This single expression works for any number of hours.</p><p>An expression is a mathematical phrase that combines numbers, variables, and operations like addition, subtraction, multiplication, and division. Unlike equations, expressions don't have an equals sign—they simply represent a value. Common examples include 3x + 5, 2a - b, or 7y². Learning to read, write, and simplify expressions is the first step toward algebraic fluency.</p><p>To evaluate an expression, we substitute a specific value for each variable and then perform the arithmetic operations. For instance, if we evaluate 3x + 5 when x = 4, we replace x with 4 to get 3(4) + 5 = 12 + 5 = 17. Practicing this substitution process builds the intuition needed for more advanced algebraic thinking.</p><p>Variables appear everywhere in real life. Scientists use them to model physical phenomena, economists track market variables, and engineers rely on variable expressions to design structures. By mastering variables and expressions now, you are laying the groundwork for virtually every branch of advanced mathematics you will encounter in your academic and professional life.</p>` },
      { title: 'Solving One-Step Equations', duration: 20, order: 2, content: `<h3>The Balance Method</h3><p>An equation is a mathematical statement asserting that two expressions are equal. The equals sign is like a balance scale: whatever you do to one side, you must do to the other side to keep the equation balanced. One-step equations require only a single operation to isolate the variable and find its value. This makes them the perfect starting point for learning how to solve equations systematically.</p><p>When a variable is added to a number, we isolate it by subtracting that number from both sides. For example, in x + 7 = 12, we subtract 7 from both sides to get x = 5. When a number is subtracted from a variable, we add to isolate it: if x - 3 = 8, we add 3 to both sides to get x = 11. Always check your answer by substituting it back into the original equation to verify balance.</p><p>Multiplication and division work similarly. If 4x = 20, we divide both sides by 4 to get x = 5. If x/3 = 6, we multiply both sides by 3 to get x = 18. The key principle remains constant: perform the inverse operation of whatever is being done to the variable. Addition and subtraction are inverses; multiplication and division are inverses.</p><p>Mastering one-step equations builds confidence and forms the basis for multi-step equations, systems of equations, and eventually calculus and beyond. Take time to practice with a variety of problems—positive numbers, negative numbers, fractions, and decimals—until solving one-step equations feels natural and automatic. The more you practice, the faster and more accurately you will solve more complex problems later.</p>` },
      { title: 'Linear Equations and Their Solutions', duration: 20, order: 3, content: `<h3>Multi-Step Linear Equations</h3><p>A linear equation in one variable is an equation that can be written in the form ax + b = c, where a, b, and c are real numbers and a ≠ 0. The solution to a linear equation is the value of the variable that makes the equation true. Unlike one-step equations, multi-step linear equations require two or more operations to isolate the variable, demanding careful, organized work at each step.</p><p>The standard strategy for solving multi-step linear equations is to first simplify each side by combining like terms, then use addition or subtraction to get all variable terms on one side and all constants on the other, and finally divide or multiply to isolate the variable. For example: 3x + 5 = 2x + 9. Subtract 2x from both sides: x + 5 = 9. Subtract 5 from both sides: x = 4. Always verify by substituting back: 3(4) + 5 = 17 and 2(4) + 9 = 17. ✓</p><p>Special cases are important to recognize. If simplification leads to a true statement with no variables—such as 5 = 5—the equation has infinitely many solutions (all real numbers). If it leads to a false statement—such as 3 = 7—the equation has no solution. Understanding these cases prevents confusion and builds deeper mathematical reasoning skills.</p><p>Real-world applications of linear equations include calculating travel time at a constant speed, finding break-even points in business, and determining temperatures in physics. The skill of translating a word problem into a linear equation and then solving it systematically is one of the most powerful tools in applied mathematics. Practice diverse problem types to build this translation skill alongside your computational fluency.</p>` },
      { title: 'Graphing on the Coordinate Plane', duration: 15, order: 4, content: `<h3>The Cartesian Coordinate System</h3><p>The coordinate plane, also called the Cartesian plane, is a two-dimensional surface defined by two perpendicular number lines: the horizontal x-axis and the vertical y-axis. Their intersection point is called the origin, labeled (0, 0). Every point on the plane is identified by an ordered pair (x, y), where x is the horizontal distance from the origin and y is the vertical distance. Understanding this system is essential for visualizing algebraic relationships graphically.</p><p>To plot a point, start at the origin, move x units horizontally (right if x is positive, left if negative), then move y units vertically (up if y is positive, down if negative). For example, to plot (3, -2), move 3 units right and 2 units down. The four quadrants of the plane are numbered I through IV counterclockwise, and knowing which quadrant a point lies in helps you check your work quickly during graphing exercises.</p><p>Linear equations in two variables, such as y = 2x + 1, produce straight-line graphs. To graph a line, you only need two points: choose two values of x, calculate the corresponding y values, plot the resulting ordered pairs, and draw a line through them. The slope of the line (rise over run) tells you how steeply it inclines, while the y-intercept tells you where it crosses the y-axis. These two characteristics completely define any non-vertical line.</p><p>Graphical representations of equations provide visual intuition that pure algebra cannot. By looking at a graph, you can immediately see whether two lines are parallel, perpendicular, or intersecting, and you can estimate solutions visually before computing them algebraically. Developing fluency in moving between algebraic and graphical representations is a hallmark of strong mathematical thinking and will serve you in every quantitative field you pursue.</p>` },
      { title: 'Systems of Linear Equations', duration: 20, order: 5, content: `<h3>Solving Systems of Equations</h3><p>A system of linear equations consists of two or more equations with the same variables. The solution to a system is the set of values that satisfies all equations simultaneously. Geometrically, each equation represents a line, and the solution is the point where the lines intersect. Systems of equations arise naturally whenever two different constraints must be satisfied at the same time—for example, finding a price and quantity that balance supply and demand in economics.</p><p>The substitution method is ideal when one equation is already solved for a variable. Substitute that expression into the other equation, solve for the remaining variable, then back-substitute to find the first. For example: y = 2x + 1 and 3x + y = 11. Substitute y: 3x + (2x + 1) = 11 → 5x = 10 → x = 2. Then y = 2(2) + 1 = 5. Solution: (2, 5). Verify in both original equations to confirm.</p><p>The elimination method adds or subtracts equations to cancel one variable. Multiply one or both equations by constants so that the coefficients of one variable are opposites, then add the equations. For example: 2x + 3y = 12 and 4x - 3y = 6. Adding gives 6x = 18 → x = 3. Substituting back: 2(3) + 3y = 12 → y = 2. Solution: (3, 2). Elimination is especially efficient when coefficients are already convenient.</p><p>Systems can have one solution (intersecting lines), no solution (parallel lines), or infinitely many solutions (identical lines). Recognizing these cases algebraically—contradiction versus identity—deepens your understanding of linear relationships. Applications include mixture problems, distance-rate-time problems, and network flow analysis. Practicing both substitution and elimination will give you flexibility to choose the most efficient method for each problem you encounter.</p>` },
    ],
    quizzes: [
      {
        title: 'Algebra Foundations - Assessment Quiz 1',
        lesson: null,
        passingScore: 70,
        questions: [
          { questionText: 'What is the value of x if 2x + 6 = 14?', options: [{ text: 'x = 2' }, { text: 'x = 3' }, { text: 'x = 4', isCorrect: true }, { text: 'x = 8' }], explanation: 'Subtract 6 from both sides: 2x = 8. Divide by 2: x = 4.' },
          { questionText: 'Which expression represents "three times a number n decreased by seven"?', options: [{ text: '3 + n - 7' }, { text: '3n - 7', isCorrect: true }, { text: '7 - 3n' }, { text: '3(n + 7)' }], explanation: '"Three times n" is 3n, and "decreased by seven" means we subtract 7, giving 3n - 7.' },
          { questionText: 'Evaluate 4a - 2b when a = 3 and b = 5.', options: [{ text: '2', isCorrect: true }, { text: '10' }, { text: '22' }, { text: '-2' }], explanation: '4(3) - 2(5) = 12 - 10 = 2.' },
          { questionText: 'Solve: x/4 = 9', options: [{ text: 'x = 36', isCorrect: true }, { text: 'x = 2.25' }, { text: 'x = 13' }, { text: 'x = 9' }], explanation: 'Multiply both sides by 4: x = 36.' },
          { questionText: 'Which point lies on the line y = 2x - 1?', options: [{ text: '(1, 1)', isCorrect: true }, { text: '(2, 2)' }, { text: '(0, 1)' }, { text: '(3, 4)' }], explanation: 'Check (1,1): y = 2(1) - 1 = 1. ✓ Other points do not satisfy the equation.' },
        ],
      },
      {
        title: 'Algebra Foundations - Lesson 3 Quiz',
        lessonIndex: 2,
        passingScore: 70,
        questions: [
          { questionText: 'Solve: 3x + 5 = 20', options: [{ text: 'x = 3' }, { text: 'x = 5', isCorrect: true }, { text: 'x = 7' }, { text: 'x = 8' }], explanation: 'Subtract 5: 3x = 15. Divide by 3: x = 5.' },
          { questionText: 'What is the solution to 2x - 3 = x + 4?', options: [{ text: 'x = 1' }, { text: 'x = 7', isCorrect: true }, { text: 'x = -7' }, { text: 'x = 4' }], explanation: 'Subtract x: x - 3 = 4. Add 3: x = 7.' },
          { questionText: 'If 5(x - 2) = 15, what is x?', options: [{ text: 'x = 1' }, { text: 'x = 3' }, { text: 'x = 5', isCorrect: true }, { text: 'x = 7' }], explanation: 'Divide by 5: x - 2 = 3. Add 2: x = 5.' },
          { questionText: 'Which equation has no solution?', options: [{ text: '2x + 3 = 7' }, { text: 'x + 5 = 5' }, { text: '2(x+1) = 2x + 3', isCorrect: true }, { text: '3x = 9' }], explanation: '2(x+1) = 2x + 3 simplifies to 2x + 2 = 2x + 3, or 2 = 3, which is false—no solution.' },
          { questionText: 'Solve: -4x + 8 = -12', options: [{ text: 'x = 1' }, { text: 'x = -1' }, { text: 'x = 5', isCorrect: true }, { text: 'x = -5' }], explanation: 'Subtract 8: -4x = -20. Divide by -4: x = 5.' },
        ],
      },
    ],
  },
  {
    title: 'Advanced Geometry',
    category: 'Mathematics',
    level: 'Intermediate',
    description: 'Explore complex geometric concepts including proofs, transformations, and coordinate geometry. This course challenges students to think spatially and develop rigorous mathematical reasoning. Ideal for learners ready to elevate their mathematical thinking.',
    tags: ['geometry', 'proofs', 'math', 'spatial'],
    lessons: [
      { title: 'Geometric Proofs and Reasoning', duration: 20, order: 1, content: `<h3>The Art of Mathematical Proof</h3><p>A geometric proof is a logical argument that establishes the truth of a geometric statement using definitions, postulates, and previously proven theorems. Proofs are the backbone of mathematics, transforming intuition into certainty. In geometry, we typically use two-column proofs—with statements on the left and reasons on the right—or paragraph proofs that read like formal arguments. Learning to write proofs develops critical thinking skills applicable far beyond mathematics.</p><p>Every proof begins with given information—the facts we know to be true—and ends with the statement we wish to prove. Between these endpoints, we construct a chain of logical steps, each justified by a definition, postulate, or theorem. Common reasons include the Reflexive Property (a thing equals itself), the Symmetric Property, the Transitive Property, and the Substitution Property. These foundational tools appear repeatedly in geometric reasoning.</p><p>Triangle congruence is one of the richest areas for geometric proof. The congruence postulates—SSS (Side-Side-Side), SAS (Side-Angle-Side), ASA (Angle-Side-Angle), AAS (Angle-Angle-Side), and HL (Hypotenuse-Leg for right triangles)—allow us to prove that two triangles are congruent and then conclude that their corresponding parts are equal. The CPCTC abbreviation (Corresponding Parts of Congruent Triangles are Congruent) is an indispensable final step in many triangle proofs.</p><p>Developing proof-writing skill requires patience and practice. Begin by working through simple direct proofs, then progress to indirect proofs (proof by contradiction) and proofs involving multiple steps. Over time you will recognize common patterns and strategies, making each new proof easier than the last. The discipline of geometric proof is excellent preparation for formal mathematical writing in any advanced field.</p>` },
      { title: 'Triangles: Properties and Theorems', duration: 15, order: 2, content: `<h3>Triangle Fundamentals</h3><p>Triangles are the simplest polygons and arguably the most important shapes in all of geometry. A triangle is determined by three vertices, three sides, and three interior angles. The Triangle Angle Sum Theorem states that the interior angles of any triangle always sum to 180°. This seemingly simple fact has profound consequences and serves as the foundation for calculating unknown angles in complex geometric figures.</p><p>Triangles are classified by their angles: acute (all angles less than 90°), right (one angle exactly 90°), or obtuse (one angle greater than 90°). They are also classified by their sides: equilateral (all sides equal, all angles 60°), isosceles (two sides equal, two base angles equal), or scalene (all sides different). The Isosceles Triangle Theorem and its converse establish the important relationship between equal sides and equal base angles.</p><p>The Pythagorean Theorem—perhaps the most famous theorem in all of mathematics—states that in a right triangle with legs a and b and hypotenuse c, a² + b² = c². This theorem, known to ancient civilizations worldwide, enables calculation of any side of a right triangle when the other two are known. Its converse is equally powerful: if a² + b² = c² in a triangle, then the triangle must be a right triangle.</p><p>Special right triangles arise frequently in geometry and trigonometry. The 45-45-90 triangle has legs in ratio 1:1:√2, and the 30-60-90 triangle has sides in ratio 1:√3:2. Memorizing these ratios allows rapid calculation without repeated use of the Pythagorean Theorem. These special triangles appear everywhere from architecture and engineering to physics and computer graphics.</p>` },
      { title: 'Circles: Arcs, Chords, and Angles', duration: 20, order: 3, content: `<h3>The Geometry of Circles</h3><p>A circle is the set of all points in a plane equidistant from a fixed center point. The distance from the center to any point on the circle is the radius; the distance across the circle through the center is the diameter, equal to twice the radius. The circumference (perimeter) of a circle equals 2πr, and its area equals πr². These fundamental formulas appear in countless applied problems across science and engineering.</p><p>An arc is a portion of the circle's circumference. A central angle has its vertex at the center of the circle, and its degree measure equals the degree measure of the intercepted arc. An inscribed angle has its vertex on the circle, and—by the Inscribed Angle Theorem—its measure equals half the intercepted arc. This elegant relationship simplifies many circle problems that would otherwise require extensive calculation.</p><p>Chords, secants, and tangents create additional angle relationships. When two chords intersect inside a circle, the measure of the angle formed equals half the sum of the intercepted arcs. When two secants, two tangents, or a secant and tangent meet outside the circle, the angle measure equals half the (positive) difference of the intercepted arcs. These theorems, though initially complex, follow naturally from the Inscribed Angle Theorem.</p><p>Circle theorems have practical applications in engineering (gear design, wheel mechanics), astronomy (planetary orbits), and art (geometric design, perspective drawing). Understanding the relationships among arcs, chords, tangents, and angles provides both computational tools and deep aesthetic appreciation for the perfect symmetry of the circle. Spend time practicing each theorem with numerical examples before moving on to proof-based problems.</p>` },
      { title: 'Transformations in the Plane', duration: 15, order: 4, content: `<h3>Geometric Transformations</h3><p>A transformation is a function that maps every point of a figure to a new location called its image. The four fundamental geometric transformations are translations, reflections, rotations, and dilations. The first three are called rigid motions or isometries because they preserve distance and angle measure—the image is congruent to the original. Dilations preserve shape but change size, producing similar figures rather than congruent ones.</p><p>A translation slides every point of a figure the same distance in the same direction. We describe a translation using a vector: T(x, y) = (x + a, y + b) shifts every point right by a units and up by b units. A reflection flips a figure across a line of reflection (the axis). Reflection across the x-axis maps (x, y) to (x, -y); across the y-axis it maps to (-x, y); across y = x it maps to (y, x). Recognizing these standard reflections speeds up calculations greatly.</p><p>A rotation turns a figure around a fixed center point through a given angle. Rotations of 90°, 180°, and 270° counterclockwise around the origin follow specific formulas: 90° maps (x, y) to (-y, x); 180° maps to (-x, -y); 270° maps to (y, -x). A dilation with center at the origin and scale factor k maps (x, y) to (kx, ky). If k > 1 the figure enlarges; if 0 < k < 1 it shrinks; if k < 0 it also reflects.</p><p>Transformations are foundational in computer graphics, animation, and robotics. Every movement you see in a video game—a character walking, a camera panning, an object scaling—is governed by mathematical transformations. Symmetry, one of the most aesthetically powerful concepts in art and science, is defined precisely in terms of transformations. Mastering transformations gives you tools to analyze patterns in nature and create them in technology.</p>` },
      { title: 'Coordinate Geometry and Distance', duration: 20, order: 5, content: `<h3>Geometry Meets Algebra</h3><p>Coordinate geometry, or analytic geometry, unifies algebra and geometry by representing geometric figures as equations and geometric relationships as algebraic conditions. The key bridge is the coordinate plane, where every point is an ordered pair and every curve is a set of points satisfying an equation. This unified framework, developed by René Descartes in the 17th century, enabled enormous advances in both mathematics and physics.</p><p>The Distance Formula gives the distance between two points (x₁, y₁) and (x₂, y₂) as d = √[(x₂-x₁)² + (y₂-y₁)²]. This formula follows directly from the Pythagorean Theorem and allows us to compute lengths, verify congruence, and classify triangles (by comparing side lengths) using only coordinates. The Midpoint Formula M = ((x₁+x₂)/2, (y₁+y₂)/2) finds the point exactly halfway between two given points.</p><p>Lines in the coordinate plane are characterized by their slope m = (y₂-y₁)/(x₂-x₁) and y-intercept b, giving the slope-intercept form y = mx + b. Parallel lines have equal slopes; perpendicular lines have slopes that are negative reciprocals of each other (m₁ · m₂ = -1). These relationships allow us to write equations of parallel or perpendicular lines given a point and a reference line.</p><p>Coordinate geometry enables powerful problem-solving strategies: placing figures in convenient positions on the coordinate plane to exploit symmetry, using the Distance Formula to prove segments are equal, and using slope to prove angles are right angles. This approach—sometimes called coordinate proof—complements traditional axiomatic proof and is essential preparation for calculus, linear algebra, and computer science algorithms involving geometric data.</p>` },
    ],
    quizzes: [
      {
        title: 'Advanced Geometry - Assessment Quiz 1',
        lesson: null,
        passingScore: 70,
        questions: [
          { questionText: 'What is the sum of interior angles of a triangle?', options: [{ text: '90°' }, { text: '180°', isCorrect: true }, { text: '270°' }, { text: '360°' }], explanation: 'The Triangle Angle Sum Theorem states that interior angles always sum to 180°.' },
          { questionText: 'In a right triangle with legs 3 and 4, what is the hypotenuse?', options: [{ text: '5', isCorrect: true }, { text: '6' }, { text: '7' }, { text: '3.5' }], explanation: 'Using the Pythagorean Theorem: 3² + 4² = 9 + 16 = 25, so c = √25 = 5.' },
          { questionText: 'A translation moves every point by the same ___.', options: [{ text: 'angle' }, { text: 'center' }, { text: 'vector', isCorrect: true }, { text: 'radius' }], explanation: 'A translation is defined by a vector that specifies the direction and magnitude of the slide.' },
          { questionText: 'What is the distance between points (1,2) and (4,6)?', options: [{ text: '3' }, { text: '4' }, { text: '5', isCorrect: true }, { text: '7' }], explanation: 'd = √[(4-1)² + (6-2)²] = √[9 + 16] = √25 = 5.' },
          { questionText: 'An inscribed angle intercepts an arc of 80°. What is the angle measure?', options: [{ text: '80°' }, { text: '160°' }, { text: '40°', isCorrect: true }, { text: '20°' }], explanation: 'By the Inscribed Angle Theorem, an inscribed angle equals half the intercepted arc: 80°/2 = 40°.' },
        ],
      },
      {
        title: 'Advanced Geometry - Lesson 3 Quiz',
        lessonIndex: 2,
        passingScore: 70,
        questions: [
          { questionText: 'A central angle of 60° intercepts an arc. What is the arc measure?', options: [{ text: '30°' }, { text: '60°', isCorrect: true }, { text: '120°' }, { text: '180°' }], explanation: 'A central angle equals the intercepted arc measure, so the arc is also 60°.' },
          { questionText: 'What is the formula for the circumference of a circle with radius r?', options: [{ text: 'πr²' }, { text: '2πr', isCorrect: true }, { text: '4πr' }, { text: 'πr' }], explanation: 'The circumference formula is C = 2πr.' },
          { questionText: 'Two chords intersect inside a circle. The intercepted arcs are 80° and 40°. What is the angle formed?', options: [{ text: '40°' }, { text: '60°', isCorrect: true }, { text: '80°' }, { text: '120°' }], explanation: 'The angle = (arc₁ + arc₂)/2 = (80° + 40°)/2 = 60°.' },
          { questionText: 'A tangent and a chord meet at a point on a circle, intercepting an arc of 140°. What is the angle between them?', options: [{ text: '70°', isCorrect: true }, { text: '140°' }, { text: '35°' }, { text: '110°' }], explanation: 'The tangent-chord angle equals half the intercepted arc: 140°/2 = 70°.' },
          { questionText: 'The area of a circle with diameter 10 is?', options: [{ text: '10π' }, { text: '20π' }, { text: '25π', isCorrect: true }, { text: '100π' }], explanation: 'Radius = 5. Area = π(5²) = 25π.' },
        ],
      },
    ],
  },
  {
    title: 'Physics: Motion & Forces',
    category: 'Science',
    level: 'Beginner',
    description: 'Discover the laws governing motion and forces in the physical world. From Newton\'s laws to real-world applications, this course makes physics accessible and engaging for all learners. Build a strong conceptual and quantitative understanding of mechanics.',
    tags: ['physics', 'motion', 'forces', 'newton'],
    lessons: [
      { title: 'Introduction to Kinematics', duration: 15, order: 1, content: `<h3>The Study of Motion</h3><p>Kinematics is the branch of physics that describes how objects move without asking why they move. It studies quantities like position, displacement, velocity, speed, and acceleration. Understanding kinematics is essential because motion is everywhere—from a ball rolling across a floor to planets orbiting the sun. By establishing precise mathematical definitions for these quantities, kinematics provides a rigorous language for describing all mechanical phenomena.</p><p>Position describes where an object is located relative to a reference point, typically the origin of a coordinate system. Displacement is the change in position: Δx = x_final - x_initial. Importantly, displacement is a vector—it has both magnitude and direction—while distance is the total path length traveled and is always positive. A car that drives 5 km east and then 5 km back west has traveled a distance of 10 km but has zero displacement.</p><p>Velocity is the rate of change of position: v = Δx/Δt. Like displacement, velocity is a vector with both magnitude (speed) and direction. Speed is the magnitude of velocity and is always non-negative. Average velocity considers only initial and final positions; instantaneous velocity describes motion at a precise moment in time. These distinctions matter greatly in problem-solving because real motion is rarely uniform.</p><p>Acceleration is the rate of change of velocity: a = Δv/Δt. An object accelerates not only when it speeds up, but also when it slows down (negative acceleration or deceleration) or changes direction. The equations of kinematics—the famous "SUVAT" equations—relate displacement, initial velocity, final velocity, acceleration, and time in powerful formulas that allow us to solve a wide range of motion problems without directly observing the motion.</p>` },
      { title: "Newton's Laws of Motion", duration: 20, order: 2, content: `<h3>The Foundation of Classical Mechanics</h3><p>Sir Isaac Newton's three laws of motion, published in 1687 in his landmark work Principia Mathematica, form the foundation of classical mechanics. These laws describe the relationship between the forces acting on an object and its resulting motion. For over two centuries they were considered the complete description of all mechanical phenomena, and they remain extraordinarily accurate for everyday speeds and scales—from a thrown baseball to a launched rocket.</p><p>Newton's First Law—the Law of Inertia—states that an object at rest stays at rest, and an object in motion stays in motion with the same speed and direction, unless acted upon by an unbalanced external force. This law reveals that the natural state of motion is constant velocity (including zero), not rest as previously believed. Inertia is the tendency of an object to resist changes to its state of motion, and it is directly proportional to mass.</p><p>Newton's Second Law quantifies how forces affect motion: the net force acting on an object equals the product of its mass and acceleration, F = ma. This elegantly simple equation explains why a small force can accelerate a light object easily, while the same force barely affects a massive one. It allows us to predict the acceleration of any object if we know its mass and the net force acting on it, making it the primary computational tool of mechanics.</p><p>Newton's Third Law states that for every action, there is an equal and opposite reaction. When you push a wall, the wall pushes back on you with equal force—that is why you do not pass through it. This law has profound implications: forces always come in pairs, and one object can never exert a force on another without experiencing an equal and opposite force in return. Rocket propulsion, swimming, and walking all depend on this third law.</p>` },
      { title: 'Friction, Normal Force, and Free Body Diagrams', duration: 20, order: 3, content: `<h3>Analyzing Forces Systematically</h3><p>A free body diagram (FBD) is a simplified sketch that represents an object as a dot and shows all the forces acting on it as arrows pointing in their respective directions. Drawing an accurate free body diagram is the essential first step in solving any mechanics problem. It prevents confusion, organizes information visually, and makes applying Newton's Second Law straightforward. Every force shown must have a physical agent—something that is actually exerting that force on the object.</p><p>The normal force is the perpendicular contact force that a surface exerts on an object resting on it. On a flat horizontal surface, the normal force is equal in magnitude to the object's weight (N = mg), pointing upward to balance gravity. On an inclined plane, the normal force is perpendicular to the surface: N = mg cos(θ), where θ is the angle of inclination. Getting the direction and magnitude of the normal force right is critical for every surface-contact problem.</p><p>Friction is a resistive force that opposes relative motion (or tends to prevent it) between surfaces in contact. Static friction acts when surfaces are stationary relative to each other and can vary from zero up to its maximum value: f_s ≤ μ_s N. Kinetic friction acts when surfaces slide relative to each other and has a constant value: f_k = μ_k N. The coefficients of friction μ_s and μ_k are dimensionless constants that depend on the materials in contact; typically μ_s > μ_k.</p><p>Applying Newton's Second Law from a free body diagram involves resolving all forces into components along convenient coordinate axes, then writing ΣF = ma for each axis. On an inclined plane, choosing axes parallel and perpendicular to the surface simplifies the algebra enormously. Systematic application of this procedure solves problems that initially appear complex—blocks on ramps, connected masses, and pulley systems all yield to this methodical approach.</p>` },
      { title: 'Work, Energy, and Power', duration: 15, order: 4, content: `<h3>Energy and Its Transformations</h3><p>Work is defined as the product of force and displacement in the direction of the force: W = Fd cos(θ), where θ is the angle between the force vector and the displacement vector. Work is a scalar quantity measured in joules (J). Importantly, if the force is perpendicular to displacement (θ = 90°), no work is done—a centripetal force, for instance, does zero work on an object moving in a circle because the force always points toward the center while motion is tangential.</p><p>Kinetic energy is the energy of motion: KE = ½mv². Potential energy is stored energy due to position or configuration. Gravitational potential energy near Earth's surface is PE = mgh, where h is height above a reference level. The Work-Energy Theorem states that the net work done on an object equals its change in kinetic energy: W_net = ΔKE. This theorem provides a powerful alternative to Newton's Second Law for problems involving varying forces or curved paths.</p><p>The Law of Conservation of Energy states that energy cannot be created or destroyed, only transformed from one form to another. In a system with only conservative forces (like gravity), mechanical energy—the sum of kinetic and potential energy—remains constant: KE₁ + PE₁ = KE₂ + PE₂. This conservation principle allows us to solve complex problems by comparing the energy at just two points, bypassing all the intermediate details of the motion.</p><p>Power is the rate at which work is done: P = W/t = Fv. It is measured in watts (W), where 1 W = 1 J/s. A powerful engine can do the same work as a less powerful one, but in less time. Understanding power is crucial in engineering applications—the power ratings of motors, engines, and generators determine their practical usefulness. Efficiency, defined as useful power output divided by total power input, quantifies how well a machine converts energy from one form to another.</p>` },
      { title: 'Circular Motion and Gravitation', duration: 20, order: 5, content: `<h3>Motion in a Circle</h3><p>When an object moves in a circle at constant speed, its direction changes continuously, meaning its velocity changes even though its speed does not. Therefore, the object is accelerating. This centripetal acceleration always points toward the center of the circle: a_c = v²/r. The net force producing this centripetal acceleration—the centripetal force—also points toward the center: F_c = mv²/r. This force is not a new type of force; it is simply the net inward force, which could be tension, gravity, friction, or a normal force depending on the situation.</p><p>Common examples of circular motion include a car rounding a curve (friction provides centripetal force), a satellite orbiting Earth (gravity provides centripetal force), and a ball on a string (tension provides centripetal force). In each case, identifying what force acts as the centripetal force and applying F_c = mv²/r allows us to solve for unknown quantities like minimum speed, maximum radius, or required force magnitude.</p><p>Newton's Law of Universal Gravitation states that every mass attracts every other mass with a force proportional to the product of their masses and inversely proportional to the square of the distance between them: F = Gm₁m₂/r². The universal gravitational constant G = 6.674 × 10⁻¹¹ N·m²/kg² is one of the fundamental constants of nature. This law explains the orbits of planets, moons, and satellites, and it shows why heavier objects don't fall faster—in a vacuum, all objects accelerate at g = GM_Earth/R_Earth² ≈ 9.8 m/s² regardless of mass.</p><p>Kepler's three laws of planetary motion—elliptical orbits, equal areas in equal times, and the period-radius relationship T² ∝ r³—follow naturally from Newton's Law of Gravitation. These laws, originally empirical generalizations discovered before Newton's time, are now understood as mathematical consequences of the inverse-square law. This unification of terrestrial and celestial mechanics was one of the greatest triumphs in the history of science.</p>` },
    ],
    quizzes: [
      {
        title: 'Physics: Motion & Forces - Assessment Quiz 1',
        lesson: null,
        passingScore: 70,
        questions: [
          { questionText: 'An object moves 30 m in 5 seconds. What is its average speed?', options: [{ text: '5 m/s' }, { text: '6 m/s', isCorrect: true }, { text: '10 m/s' }, { text: '150 m/s' }], explanation: 'Average speed = distance/time = 30/5 = 6 m/s.' },
          { questionText: "Newton's Second Law states F = ?", options: [{ text: 'mv' }, { text: 'ma', isCorrect: true }, { text: 'm/a' }, { text: 'v/t' }], explanation: "Newton's Second Law: Force = mass × acceleration, F = ma." },
          { questionText: 'What is kinetic energy of a 2 kg object moving at 4 m/s?', options: [{ text: '8 J' }, { text: '16 J', isCorrect: true }, { text: '4 J' }, { text: '32 J' }], explanation: 'KE = ½mv² = ½(2)(4²) = ½(2)(16) = 16 J.' },
          { questionText: 'Centripetal acceleration always points:', options: [{ text: 'Away from center' }, { text: 'Toward center', isCorrect: true }, { text: 'Along the tangent' }, { text: 'Downward' }], explanation: 'Centripetal acceleration points toward the center of the circular path.' },
          { questionText: "Newton's First Law describes the concept of:", options: [{ text: 'Force' }, { text: 'Acceleration' }, { text: 'Inertia', isCorrect: true }, { text: 'Momentum' }], explanation: "Newton's First Law is the Law of Inertia: objects resist changes to their state of motion." },
        ],
      },
      {
        title: 'Physics: Motion & Forces - Lesson 3 Quiz',
        lessonIndex: 2,
        passingScore: 70,
        questions: [
          { questionText: 'What does a free body diagram show?', options: [{ text: 'The path of motion' }, { text: 'All forces acting on an object', isCorrect: true }, { text: 'Only the weight' }, { text: 'The object\'s velocity' }], explanation: 'A free body diagram represents all forces acting on an object as arrows.' },
          { questionText: 'On a flat surface, the normal force on a 5 kg object equals?', options: [{ text: '5 N' }, { text: '49 N', isCorrect: true }, { text: '9.8 N' }, { text: '50 N' }], explanation: 'N = mg = 5 × 9.8 = 49 N.' },
          { questionText: 'Kinetic friction is described by f_k = ?', options: [{ text: 'μ_s N' }, { text: 'μ_k N', isCorrect: true }, { text: 'μ_k m' }, { text: 'μ_s mg' }], explanation: 'Kinetic friction force = coefficient of kinetic friction × normal force.' },
          { questionText: 'Static friction is always _____ kinetic friction.', options: [{ text: 'Equal to' }, { text: 'Less than' }, { text: 'Greater than or equal to', isCorrect: true }, { text: 'Independent of' }], explanation: 'The maximum static friction is typically greater than kinetic friction: μ_s ≥ μ_k.' },
          { questionText: 'A 10 kg box rests on a surface with μ_k = 0.3. What is the kinetic friction force?', options: [{ text: '3 N' }, { text: '29.4 N', isCorrect: true }, { text: '0.3 N' }, { text: '10 N' }], explanation: 'f_k = μ_k × N = 0.3 × (10 × 9.8) = 0.3 × 98 = 29.4 N.' },
        ],
      },
    ],
  },
  {
    title: 'Human Biology & Anatomy',
    category: 'Science',
    level: 'Intermediate',
    description: 'Journey through the human body system by system. This course covers anatomy, physiology, and the incredible mechanisms that keep us alive and functioning every day. Gain a deep appreciation for the elegance and complexity of the human biological machine.',
    tags: ['biology', 'anatomy', 'health', 'science'],
    lessons: [
      { title: 'The Cell: Basic Unit of Life', duration: 10, order: 1, content: `<h3>Life at the Cellular Level</h3><p>The cell is the fundamental structural and functional unit of all living organisms. Human beings are composed of approximately 37 trillion cells, each microscopic in size yet astoundingly complex in function. Cell theory, formulated in the 19th century, states that all living things are made of cells, the cell is the basic unit of life, and all cells arise from pre-existing cells. This theory is one of the great unifying principles of biology.</p><p>Human cells are eukaryotic—they possess a membrane-bound nucleus that contains genetic material (DNA) organized into chromosomes. The cell membrane, composed of a phospholipid bilayer embedded with proteins, regulates the passage of substances into and out of the cell. The cytoplasm—the gel-like fluid filling the cell—contains numerous organelles, each with specialized functions analogous to the organs of a whole organism.</p><p>Key organelles include the mitochondria ("powerhouses" that generate ATP through cellular respiration), ribosomes (sites of protein synthesis), the endoplasmic reticulum (network for protein and lipid processing), the Golgi apparatus (packaging and shipping center for proteins), and lysosomes (containing digestive enzymes). The cytoskeleton—a network of protein filaments—gives the cell its shape and enables movement and internal transport.</p><p>Cell division is essential for growth, repair, and reproduction. Mitosis produces two genetically identical daughter cells and is responsible for normal body growth and tissue repair. Meiosis produces four genetically diverse gametes (sperm and eggs) and is the basis of sexual reproduction. Errors in cell division can lead to cancer—uncontrolled cell proliferation that threatens the organism. Understanding cellular biology is the foundation for virtually every area of medicine and biotechnology.</p>` },
      { title: 'The Cardiovascular System', duration: 20, order: 2, content: `<h3>The Heart and Blood Vessels</h3><p>The cardiovascular system consists of the heart, blood vessels (arteries, veins, and capillaries), and blood. Its primary function is to transport oxygen, nutrients, hormones, and immune cells to every tissue in the body while removing carbon dioxide and metabolic waste products. The average adult heart beats approximately 100,000 times per day, pumping roughly 5 liters of blood per minute at rest—an astonishing feat of biological engineering that runs continuously for decades without rest.</p><p>The heart is a four-chambered muscular pump. The right atrium receives deoxygenated blood from the body via the superior and inferior vena cavae; the right ventricle pumps this blood to the lungs for oxygenation (pulmonary circulation). The left atrium receives oxygenated blood from the pulmonary veins; the left ventricle—the most powerful chamber—pumps this blood to the entire body (systemic circulation). Four valves prevent backflow: tricuspid, pulmonary, mitral, and aortic.</p><p>Arteries carry blood away from the heart and have thick, elastic walls to withstand high pressure. Veins carry blood toward the heart and have thinner walls and valves to prevent backflow against gravity. Capillaries—the tiniest vessels, only one cell thick—are where gas and nutrient exchange with tissues actually occurs. Blood pressure is measured as systolic (when the heart contracts) over diastolic (when it relaxes); normal adult blood pressure is approximately 120/80 mmHg.</p><p>Cardiovascular disease is the leading cause of death worldwide. Risk factors include hypertension, high cholesterol, smoking, diabetes, obesity, and physical inactivity. Understanding cardiovascular anatomy and physiology helps us appreciate why these risk factors are dangerous and how lifestyle modifications—regular exercise, a heart-healthy diet, not smoking—dramatically reduce risk. Modern medicine has developed extraordinary interventions from statins to cardiac surgery, all built upon detailed knowledge of cardiovascular biology.</p>` },
      { title: 'The Respiratory System', duration: 20, order: 3, content: `<h3>Breathing and Gas Exchange</h3><p>The respiratory system provides the body with oxygen and removes carbon dioxide, the primary waste product of cellular respiration. It consists of the airways (nose, pharynx, larynx, trachea, bronchi, bronchioles) and the lungs. The intricate branching of the airways creates an enormous surface area—approximately 70 square meters in an adult—for the rapid gas exchange that sustains life. Without a constant supply of oxygen, brain cells begin to die within minutes.</p><p>Breathing is driven by changes in chest volume created by the respiratory muscles. During inhalation, the diaphragm contracts and flattens, while the external intercostal muscles raise the rib cage—both actions increase chest volume, decrease pressure inside the lungs, and air flows in. During exhalation, these muscles relax, the chest volume decreases, pressure rises, and air flows out. This mechanical process is called ventilation and is distinct from the chemical process of gas exchange.</p><p>Gas exchange occurs in the alveoli—tiny, thin-walled air sacs at the ends of the bronchioles. Each alveolus is surrounded by a dense capillary network. Oxygen diffuses from the high-concentration alveolar air into the low-concentration blood; carbon dioxide diffuses in the opposite direction. Hemoglobin in red blood cells dramatically increases blood's oxygen-carrying capacity by binding O₂ cooperatively—when one O₂ binds to hemoglobin, the affinity for additional O₂ molecules increases, an elegant regulatory mechanism called cooperative binding.</p><p>Respiratory disorders such as asthma, COPD, pneumonia, and COVID-19 illustrate the system's vulnerability. Asthma involves inflammation and bronchoconstriction that impedes airflow; COPD destroys alveolar walls, reducing surface area for gas exchange. Understanding the respiratory system's anatomy and physiology is essential for healthcare providers and informs public health measures like air quality standards, smoking cessation programs, and ventilator management in critically ill patients.</p>` },
      { title: 'The Nervous System', duration: 15, order: 4, content: `<h3>Control and Communication</h3><p>The nervous system is the body's communication and control network, enabling rapid response to internal and external changes. It is divided into the central nervous system (CNS: brain and spinal cord) and the peripheral nervous system (PNS: all other nerves and ganglia). The basic unit is the neuron—a cell specialized to transmit electrochemical signals. The human brain contains approximately 86 billion neurons, each forming thousands of synaptic connections with other neurons, creating a network of almost incomprehensible complexity.</p><p>Neurons communicate via action potentials—rapid, self-propagating electrical signals generated by the controlled flow of sodium, potassium, and other ions across the cell membrane. The resting membrane potential is approximately -70 mV. When a sufficient stimulus depolarizes the membrane to the threshold of about -55 mV, voltage-gated sodium channels open, sodium floods in, and the potential rapidly rises to +40 mV. This "all-or-nothing" signal travels down the axon at speeds up to 120 m/s in myelinated neurons.</p><p>At the synapse, the action potential triggers release of neurotransmitters—chemical messengers that cross the synaptic cleft and bind to receptors on the post-synaptic cell. Excitatory neurotransmitters (like glutamate) make the next neuron more likely to fire; inhibitory ones (like GABA) make it less likely. The balance of excitation and inhibition across billions of synapses produces thought, emotion, movement, sensation, memory, and every other aspect of conscious and unconscious brain function.</p><p>Neurological disorders—Alzheimer's, Parkinson's, epilepsy, stroke, multiple sclerosis—illustrate the catastrophic consequences of nervous system dysfunction. Modern neuroscience, combining molecular biology, imaging technology, and computational modeling, is rapidly deepening our understanding of the brain. This knowledge drives the development of new treatments for neurological and psychiatric disorders, and informs technologies such as brain-computer interfaces that may transform human capabilities in the coming decades.</p>` },
      { title: 'The Immune System', duration: 20, order: 5, content: `<h3>The Body's Defense Network</h3><p>The immune system protects the body against pathogens—bacteria, viruses, fungi, parasites, and abnormal cells like cancer. It operates through two interconnected arms: innate immunity (fast, non-specific, the first line of defense) and adaptive immunity (slower, highly specific, producing lasting immunological memory). Together they form an extraordinarily sophisticated defense network, capable of distinguishing "self" from "non-self" among millions of different molecular structures and mounting a targeted response against specific threats.</p><p>The innate immune system includes physical barriers (skin, mucous membranes), phagocytes (neutrophils and macrophages that engulf pathogens), natural killer cells (that destroy infected and cancerous cells), and the complement system (a cascade of proteins that tag pathogens for destruction). Inflammation—characterized by redness, heat, swelling, and pain—is the innate immune system's rapid response to tissue damage or infection, increasing blood flow and recruiting immune cells to the site.</p><p>The adaptive immune system involves two main cell types derived from lymphocytes. B cells produce antibodies—Y-shaped proteins that bind specifically to antigens (molecular markers on pathogens) and neutralize them or tag them for destruction. T cells include helper T cells (which coordinate the immune response), cytotoxic T cells (which kill infected cells directly), and regulatory T cells (which prevent excessive immune activity). The adaptive response takes days to develop initially but generates memory cells that enable rapid, powerful responses upon re-exposure to the same pathogen.</p><p>Vaccines exploit immunological memory—they expose the immune system to a harmless antigen, triggering the adaptive response and generating memory cells without causing disease. If the vaccinated person later encounters the actual pathogen, the memory response eliminates it before significant illness can develop. Autoimmune diseases arise when the immune system incorrectly attacks the body's own tissues; allergies arise from excessive responses to harmless substances. Understanding immune function is central to modern medicine, from vaccine development to transplant immunology to cancer immunotherapy.</p>` },
    ],
    quizzes: [
      {
        title: 'Human Biology & Anatomy - Assessment Quiz 1',
        lesson: null,
        passingScore: 70,
        questions: [
          { questionText: 'Which organelle is known as the "powerhouse of the cell"?', options: [{ text: 'Nucleus' }, { text: 'Ribosome' }, { text: 'Mitochondria', isCorrect: true }, { text: 'Golgi apparatus' }], explanation: 'Mitochondria produce ATP through cellular respiration, earning the "powerhouse" nickname.' },
          { questionText: 'The left ventricle pumps blood to:', options: [{ text: 'The lungs' }, { text: 'The right atrium' }, { text: 'The entire body', isCorrect: true }, { text: 'The left atrium' }], explanation: 'The left ventricle is the most powerful chamber and pumps oxygenated blood to the systemic circulation.' },
          { questionText: 'Gas exchange occurs in the:', options: [{ text: 'Trachea' }, { text: 'Bronchi' }, { text: 'Alveoli', isCorrect: true }, { text: 'Pharynx' }], explanation: 'Alveoli are tiny air sacs surrounded by capillaries where O₂ and CO₂ exchange occurs.' },
          { questionText: 'Antibodies are produced by:', options: [{ text: 'T cells' }, { text: 'B cells', isCorrect: true }, { text: 'Neutrophils' }, { text: 'Macrophages' }], explanation: 'B cells differentiate into plasma cells that produce antibodies specific to antigens.' },
          { questionText: 'A normal adult resting heart rate is approximately:', options: [{ text: '20-40 bpm' }, { text: '60-100 bpm', isCorrect: true }, { text: '120-140 bpm' }, { text: '150-180 bpm' }], explanation: 'A healthy resting heart rate for adults is 60-100 beats per minute.' },
        ],
      },
      {
        title: 'Human Biology & Anatomy - Lesson 3 Quiz',
        lessonIndex: 2,
        passingScore: 70,
        questions: [
          { questionText: 'What is the primary function of the respiratory system?', options: [{ text: 'Pumping blood' }, { text: 'Gas exchange', isCorrect: true }, { text: 'Digestion' }, { text: 'Hormone regulation' }], explanation: 'The respiratory system provides oxygen and removes carbon dioxide through gas exchange.' },
          { questionText: 'The diaphragm contracts during:', options: [{ text: 'Exhalation' }, { text: 'Inhalation', isCorrect: true }, { text: 'Both equally' }, { text: 'Neither' }], explanation: 'During inhalation, the diaphragm contracts and flattens to expand chest volume and draw air in.' },
          { questionText: 'Hemoglobin is found in:', options: [{ text: 'White blood cells' }, { text: 'Plasma' }, { text: 'Red blood cells', isCorrect: true }, { text: 'Platelets' }], explanation: 'Hemoglobin is the oxygen-carrying protein found inside red blood cells.' },
          { questionText: 'Surface area for gas exchange in an adult\'s lungs is approximately:', options: [{ text: '1 m²' }, { text: '10 m²' }, { text: '70 m²', isCorrect: true }, { text: '200 m²' }], explanation: 'The branching structure creates approximately 70 m² of surface area in the alveoli.' },
          { questionText: 'COPD primarily causes damage to:', options: [{ text: 'The trachea' }, { text: 'Alveolar walls', isCorrect: true }, { text: 'The diaphragm' }, { text: 'Capillaries' }], explanation: 'COPD destroys alveolar walls, reducing surface area for gas exchange.' },
        ],
      },
    ],
  },
  {
    title: 'World History: Ancient Civilizations',
    category: 'History',
    level: 'Beginner',
    description: 'Travel back in time to explore the great civilizations of the ancient world. From Mesopotamia to Rome, discover how early societies shaped our modern world through their innovations in government, law, science, and culture. History is not just the past—it is the blueprint of the present.',
    tags: ['history', 'ancient', 'civilizations', 'world history'],
    lessons: [
      { title: 'Mesopotamia: The Cradle of Civilization', duration: 15, order: 1, content: `<h3>Between the Rivers</h3><p>Mesopotamia—meaning "land between the rivers" in Greek—refers to the ancient region between the Tigris and Euphrates rivers, roughly corresponding to modern-day Iraq. Around 3500 BCE, the Sumerians developed the world's first urban civilization here, establishing cities like Uruk, Ur, and Nippur. These cities featured monumental architecture, complex social hierarchies, specialized labor, long-distance trade networks, and—crucially—the world's first writing system, called cuneiform.</p><p>Cuneiform began as pictographic symbols pressed into clay tablets to record economic transactions—who owed how much grain to whom. Over centuries it evolved into a flexible script capable of recording laws, literature, and scientific observations. The Epic of Gilgamesh, composed in Mesopotamia around 2100 BCE, is among the earliest surviving works of literature. It explores themes of friendship, loss, and the human search for immortality that remain profoundly relevant today.</p><p>Mesopotamian civilization gave the world many foundational concepts. The Code of Hammurabi (c. 1754 BCE), one of the earliest written law codes, established the principle that rulers should protect the weak and punish wrongdoers consistently—a predecessor to the rule of law. Mesopotamian astronomers developed mathematical astronomy, creating calendars, predicting eclipses, and laying the groundwork for later Greek and modern science. The 60-minute hour and 360-degree circle we use today originated in Mesopotamian mathematics.</p><p>Successive empires dominated Mesopotamia over millennia—the Akkadian Empire, the Third Dynasty of Ur, the Old Babylonian Period, the Assyrian Empire, and finally the Neo-Babylonian Empire. Each contributed innovations to governance, art, and learning. When the Persian King Cyrus the Great conquered Babylon in 539 BCE, Mesopotamian civilization merged into the broader Persian Empire, but its cultural legacy persisted and was transmitted through the Greeks to the modern West.</p>` },
      { title: 'Ancient Egypt: Pharaohs and Pyramids', duration: 20, order: 2, content: `<h3>The Gift of the Nile</h3><p>Ancient Egyptian civilization flourished along the Nile River for over three thousand years—one of the longest-lasting civilizations in human history. The annual Nile flood deposited rich silt, enabling abundant agriculture in the midst of the Sahara Desert. This agricultural surplus supported a large, specialized population including scribes, priests, artisans, soldiers, and a divine ruling class led by the pharaoh, who was considered both a god and a king. The stability of Egyptian civilization—its remarkable continuity across dynasties—derived partly from this agricultural foundation and partly from the Nile's geographic isolation, which protected Egypt from invasion.</p><p>The pharaohs of the Old Kingdom (c. 2686-2181 BCE) built the iconic pyramids as royal tombs and statements of divine power. The Great Pyramid of Giza, built for Pharaoh Khufu around 2560 BCE, stood as the tallest man-made structure on Earth for over 3,800 years. Its construction required organizing tens of thousands of workers, managing enormous logistical operations, and applying sophisticated engineering knowledge—all without modern machinery. Recent archaeological evidence suggests the pyramid builders were well-fed, skilled workers rather than the enslaved laborers of popular myth.</p><p>Egyptian religion permeated every aspect of life. The Egyptians worshipped a rich pantheon of gods—Ra (sun god), Osiris (afterlife), Isis (magic and healing), Horus (kingship), Thoth (wisdom and writing)—and believed in an elaborate afterlife requiring the preservation of the body. Mummification was a complex, expensive process reserved for elites, involving removal of organs, desiccation with natron salt, and wrapping with linen. The Book of the Dead provided spells to guide the deceased through the afterlife judgment.</p><p>Ancient Egypt made lasting contributions to world civilization. Hieroglyphic writing, deciphered by Champollion using the Rosetta Stone in 1822, has revealed a vast literature of religious texts, wisdom literature, medical treatises, and historical records. Egyptian mathematics and medicine were among the most advanced of the ancient world. Egyptian art and architecture influenced Greek, Roman, and modern aesthetic traditions. And the calendar of 365 days that Egypt developed over 3000 years ago is the direct ancestor of the Gregorian calendar we use today.</p>` },
      { title: 'Classical Greece: Democracy and Philosophy', duration: 20, order: 3, content: `<h3>The Greek Miracle</h3><p>Ancient Greece—a collection of independent city-states (poleis) sharing a common language and culture—gave the world unprecedented contributions to philosophy, science, mathematics, literature, art, and political thought. The Greek cultural explosion of the 5th and 4th centuries BCE, centered especially in Athens, is sometimes called the "Greek Miracle" for how quickly and profoundly it changed human intellectual life. The foundations of Western civilization—its rationalism, its democratic ideals, its literary and artistic traditions—are deeply Hellenic.</p><p>Athens under Cleisthenes (508 BCE) developed the world's first democracy (demos = people, kratos = power). Athenian democracy was direct rather than representative: all male citizens participated in the Assembly, debated legislation, and voted on war and peace. While limited by modern standards (excluding women, slaves, and foreigners), it established the revolutionary principle that ordinary citizens had the right to govern themselves. The Athenian experiment inspired every subsequent democratic movement, including the architects of modern constitutions.</p><p>Greek philosophy transformed human thinking. Socrates developed the Socratic Method—rigorous questioning to expose assumptions and pursue truth. His student Plato founded the Academy (the first institution of higher learning in the Western world) and wrote the dialogues that remain foundational texts of Western philosophy. Aristotle, Plato's student, systematized knowledge across biology, logic, ethics, politics, and physics, and his works dominated European intellectual life for two millennia. Together they established philosophy as a discipline of rational inquiry guided by argument rather than authority or tradition.</p><p>The Greek world gave us Homer's Iliad and Odyssey, tragedy and comedy as literary forms, the Parthenon, the Olympic Games, Euclidean geometry, Pythagorean mathematics, Hippocratic medicine, and Thucydidean history. Alexander the Great's conquests (336-323 BCE) spread Greek culture (Hellenism) across an enormous swath of the ancient world from Egypt to India, creating a cosmopolitan Mediterranean world that became the cultural foundation of the Roman Empire and, through Rome, of European and global civilization.</p>` },
      { title: 'The Roman Empire: Law and Legacy', duration: 15, order: 4, content: `<h3>From Republic to Empire</h3><p>Rome began as a small city-state on the banks of the Tiber River in central Italy, traditionally founded in 753 BCE. Over the next seven centuries, through a combination of military power, political flexibility, and cultural assimilation, it grew to dominate the entire Mediterranean world and much of Europe. The Roman Republic (509-27 BCE), governed by elected magistrates and a Senate representing the aristocracy, developed sophisticated institutions of governance that profoundly influenced later political systems, including the United States Constitution.</p><p>Roman law—codified in the Twelve Tables (450 BCE) and elaborated by generations of jurists—is one of Rome's most enduring legacies. Roman legal principles including presumption of innocence, the right to confront accusers, equality before the law, and legal personhood for organizations underlie the legal systems of most European countries and their former colonies worldwide. The term "legal" itself derives from the Latin "lex" (law), and many legal concepts in common use today—contract, property, tort, citizen—originated in Roman jurisprudence.</p><p>The Roman Empire at its height (117 CE under Trajan) stretched from Britain to Mesopotamia, from the Rhine to the Sahara—home to perhaps 70 million people. Roman engineering enabled this vast empire: roads (over 400,000 km) connected every corner of the realm, aqueducts brought fresh water to cities, concrete construction created durable buildings (some still standing 2000 years later), and the Roman army was the most disciplined and effective military force of the ancient world. Roman infrastructure so dramatically improved connectivity and productivity that many regions of Europe did not regain the economic complexity of the Roman period until the High Middle Ages.</p><p>The fall of the Western Roman Empire in 476 CE—the traditional endpoint of ancient history—was a gradual process driven by internal pressures (political instability, economic decline, disease) and external pressures (Germanic migrations and invasions). But Rome did not simply disappear: the Eastern Roman (Byzantine) Empire survived another thousand years until 1453, the Catholic Church preserved Latin culture and Roman organizational models, and throughout the Middle Ages and Renaissance, thinkers looked back to Rome as the model of civilization. We still live in the shadow of Rome—in our languages, laws, calendars, architecture, and political ideals.</p>` },
      { title: 'Ancient China and the Silk Road', duration: 20, order: 5, content: `<h3>Civilization in the East</h3><p>Chinese civilization, one of the oldest continuous civilizations on Earth, developed independently along the Yellow River (Huang He) and Yangtze River valleys. The legendary Xia Dynasty (c. 2100-1600 BCE), Shang Dynasty (c. 1600-1046 BCE) and Zhou Dynasty (1046-256 BCE) successively developed bronze metallurgy, writing, elaborate ritual religion, and sophisticated political institutions. China's isolation by deserts, mountains, and sea fostered a distinct cultural tradition that, despite periodic foreign invasions and dynastic changes, maintained remarkable continuity over millennia.</p><p>The philosophical traditions that emerged during the Zhou Dynasty's "Hundred Schools of Thought" (c. 6th-3rd centuries BCE) profoundly shaped Chinese civilization. Confucianism emphasized hierarchical social relationships, filial piety, ritual propriety, and the cultivation of virtue in rulers and subjects alike—values that structured Chinese society for over two millennia. Daoism sought harmony with the natural order through simplicity and non-action. Legalism advocated strong centralized authority and strict laws—the philosophy that guided the first Chinese emperor, Qin Shi Huang, who unified China in 221 BCE.</p><p>The Han Dynasty (206 BCE - 220 CE) is considered a golden age of Chinese civilization. The Han formalized Confucianism as the state ideology, established an examination-based meritocratic civil service, expanded Chinese territory, and initiated the Silk Road trade network. The Silk Road—a network of overland and maritime routes connecting China to Central Asia, Persia, the Roman Empire, and eventually East Africa—was not merely a road for silk but a conduit for goods, ideas, religions (Buddhism spread to China via the Silk Road), technologies, and disease that shaped civilizations across Eurasia.</p><p>Chinese technological innovations during the first millennium CE—paper, printing, gunpowder, and the compass—eventually reached Europe and transformed world history in ways the Chinese inventors could not have foreseen. Paper and printing democratized knowledge; gunpowder revolutionized warfare and mining; the compass enabled the Age of Exploration. Understanding the global transmission of these innovations via the Silk Road trade networks illustrates a crucial point: no civilization developed in isolation, and the history of the ancient world is ultimately a history of connection, exchange, and mutual influence across distances that seem vast yet were bridged by human curiosity and commerce.</p>` },
    ],
    quizzes: [
      {
        title: 'World History: Ancient Civilizations - Assessment Quiz 1',
        lesson: null,
        passingScore: 70,
        questions: [
          { questionText: 'Cuneiform writing was developed by the:', options: [{ text: 'Egyptians' }, { text: 'Sumerians', isCorrect: true }, { text: 'Greeks' }, { text: 'Romans' }], explanation: 'The Sumerians of Mesopotamia developed cuneiform—the world\'s first writing system—around 3500 BCE.' },
          { questionText: 'The Great Pyramid of Giza was built for which pharaoh?', options: [{ text: 'Ramesses II' }, { text: 'Tutankhamun' }, { text: 'Khufu', isCorrect: true }, { text: 'Cleopatra' }], explanation: 'The Great Pyramid was built as the tomb for Pharaoh Khufu (Cheops) around 2560 BCE.' },
          { questionText: 'Athenian democracy was characterized as:', options: [{ text: 'Representative democracy' }, { text: 'Direct democracy', isCorrect: true }, { text: 'Constitutional monarchy' }, { text: 'Oligarchy' }], explanation: 'Athenian democracy was direct: citizens participated personally in the Assembly rather than electing representatives.' },
          { questionText: 'Which philosophical school guided the first emperor of China?', options: [{ text: 'Confucianism' }, { text: 'Daoism' }, { text: 'Buddhism' }, { text: 'Legalism', isCorrect: true }], explanation: 'Qin Shi Huang applied Legalist principles—strong centralized authority and strict law—to unify China.' },
          { questionText: 'The Silk Road primarily connected China with:', options: [{ text: 'South America' }, { text: 'Sub-Saharan Africa' }, { text: 'Central Asia and Europe', isCorrect: true }, { text: 'Australia' }], explanation: 'The Silk Road was a network of routes connecting China to Central Asia, Persia, and eventually the Roman Empire.' },
        ],
      },
      {
        title: 'World History: Ancient Civilizations - Lesson 3 Quiz',
        lessonIndex: 2,
        passingScore: 70,
        questions: [
          { questionText: 'Who developed the Socratic Method?', options: [{ text: 'Plato' }, { text: 'Aristotle' }, { text: 'Socrates', isCorrect: true }, { text: 'Alexander' }], explanation: 'Socrates developed the method of rigorous questioning to expose assumptions and pursue truth.' },
          { questionText: 'The first democratic reforms in Athens were introduced by:', options: [{ text: 'Pericles' }, { text: 'Solon' }, { text: 'Cleisthenes', isCorrect: true }, { text: 'Themistocles' }], explanation: 'Cleisthenes introduced democratic reforms in 508 BCE, earning the title "father of Athenian democracy."' },
          { questionText: 'The Academy was founded by:', options: [{ text: 'Socrates' }, { text: 'Plato', isCorrect: true }, { text: 'Aristotle' }, { text: 'Epicurus' }], explanation: 'Plato founded the Academy in Athens around 387 BCE—one of the first institutions of higher learning.' },
          { questionText: 'Alexander the Great spread which culture across his empire?', options: [{ text: 'Roman' }, { text: 'Persian' }, { text: 'Egyptian' }, { text: 'Hellenism (Greek)', isCorrect: true }], explanation: 'Alexander\'s conquests spread Hellenism—Greek culture and language—across a vast swath of the ancient world.' },
          { questionText: 'Greek tragedy and comedy were developed as which type of art form?', options: [{ text: 'Poetry' }, { text: 'Sculpture' }, { text: 'Literary/theatrical forms', isCorrect: true }, { text: 'Painting' }], explanation: 'The Greeks pioneered tragedy and comedy as theatrical/literary art forms performed at festivals honoring Dionysus.' },
        ],
      },
    ],
  },
  {
    title: 'Python Programming Fundamentals',
    category: 'Computer Science',
    level: 'Beginner',
    description: 'Learn to code with Python from absolute scratch. This course covers variables, control flow, functions, and data structures through hands-on projects and real-world examples. Python is the world\'s most popular programming language—and this is where your journey begins.',
    tags: ['python', 'programming', 'coding', 'beginner', 'computer science'],
    lessons: [
      { title: 'Introduction to Python and Your First Program', duration: 15, order: 1, content: `<h3>Welcome to Python</h3><p>Python is a high-level, interpreted, general-purpose programming language created by Guido van Rossum and first released in 1991. It is consistently ranked as the world's most popular programming language, beloved by beginners for its clear, readable syntax and by professionals for its powerful libraries and versatility. Python is used in web development, data science, machine learning, artificial intelligence, scientific computing, automation, and countless other domains. Learning Python is one of the most valuable technical investments you can make.</p><p>Python's philosophy emphasizes code readability and simplicity. Unlike languages cluttered with curly braces, semicolons, and verbose syntax, Python uses indentation to define code blocks and reads almost like English. The Python community embraces the principle "There should be one—and preferably only one—obvious way to do it," which leads to consistent, maintainable code. The interactive Python interpreter allows you to test code line-by-line, making learning immediate and satisfying.</p><p>Your first Python program is famously simple. Open a Python file or interactive interpreter and type: print("Hello, World!") — then press Enter. The print() function displays text to the screen. This single line illustrates Python's elegance: no boilerplate, no type declarations, no class definitions required to output text. From this simple beginning, we will progressively build toward programs that can analyze data, automate tasks, and solve real problems.</p><p>Setting up your Python environment requires installing Python from python.org and optionally an Integrated Development Environment (IDE) like VS Code, PyCharm, or Thonny. The Python REPL (Read-Evaluate-Print Loop) is excellent for experimentation. For longer programs, write code in .py files and run them with the python filename.py command. As you progress, you will learn to use pip (Python's package manager) to install third-party libraries that extend Python's capabilities enormously.</p>` },
      { title: 'Variables, Data Types, and Operators', duration: 20, order: 2, content: `<h3>Working with Data in Python</h3><p>Variables in Python are created by assignment—simply write a name, an equals sign, and a value: age = 25 or name = "Alice". Python is dynamically typed, meaning you don't need to declare the type; Python infers it from the value. Variable names must begin with a letter or underscore, contain only letters, digits, and underscores, and cannot be Python keywords (like if, for, while, def). Python convention (PEP 8) recommends snake_case for variable names: first_name, total_cost, is_valid.</p><p>Python has several fundamental data types. Integers (int) are whole numbers: 42, -7, 0. Floating-point numbers (float) have decimal points: 3.14, -0.001, 2.0. Strings (str) are sequences of characters enclosed in quotes: "hello" or 'world'. Booleans (bool) are True or False. The None type represents the absence of a value. You can check any variable's type with type(variable) and convert between types with int(), float(), str(), and bool() functions.</p><p>Python supports all standard arithmetic operators: + (addition), - (subtraction), * (multiplication), / (division, always returns float), // (integer division), % (modulus, remainder), ** (exponentiation). String concatenation uses +: "Hello" + " " + "World" gives "Hello World". String multiplication uses *: "ha" * 3 gives "hahaha". Comparison operators (==, !=, <, >, <=, >=) return Boolean values. Logical operators (and, or, not) combine Boolean expressions.</p><p>Python also offers powerful string methods. len("hello") returns 5. "hello".upper() returns "HELLO". "Hello World".split() returns ["Hello", "World"]. "   hello   ".strip() removes leading and trailing whitespace. F-strings (formatted string literals) enable elegant string interpolation: f"My name is {name} and I am {age} years old." These tools make Python's string handling far more expressive and convenient than in many other languages, and mastering them will serve you well in text processing, web development, and data analysis.</p>` },
      { title: 'Control Flow: If Statements and Loops', duration: 20, order: 3, content: `<h3>Making Decisions and Repeating Actions</h3><p>Control flow determines the order in which Python executes statements. By default, Python executes statements sequentially from top to bottom. Control flow statements—if/elif/else, for loops, and while loops—allow programs to make decisions and repeat actions, enabling them to handle variable inputs and solve complex problems. Mastering control flow transforms your programs from simple scripts into responsive, dynamic tools.</p><p>The if statement executes a block of code only if a condition is True. The elif clause adds additional conditions to check if the first was False. The else clause executes if no conditions were True. In Python, indentation (4 spaces per level) defines the code block—this enforced indentation makes Python code visually clear. Example: if score >= 90: grade = 'A' / elif score >= 80: grade = 'B' / elif score >= 70: grade = 'C' / else: grade = 'F'. Nested if statements allow more complex decision trees.</p><p>The for loop iterates over a sequence—a list, string, range, or other iterable—executing its body once for each element: for i in range(5): print(i) prints 0 through 4. The range() function generates arithmetic sequences: range(start, stop, step). The while loop executes as long as a condition remains True: while balance > 0: balance -= payment. The break statement exits a loop immediately; the continue statement skips the rest of the current iteration and moves to the next. These control mechanisms give you precise command over repetition.</p><p>Combining conditions and loops enables powerful patterns. List comprehensions—a Pythonic, concise way to create lists—combine a for loop and optional condition in a single expression: squares = [x**2 for x in range(10) if x % 2 == 0] creates a list of squares of even numbers from 0-9. The enumerate() function gives both the index and value when iterating: for i, item in enumerate(my_list). The zip() function pairs elements from two lists for parallel iteration. These tools make Python loops more expressive, readable, and efficient than equivalent constructs in many other languages.</p>` },
      { title: 'Functions and Modules', duration: 15, order: 4, content: `<h3>Organizing Code with Functions</h3><p>A function is a named, reusable block of code that performs a specific task. Functions are defined using the def keyword, followed by the function name, parameters in parentheses, a colon, and an indented body. Parameters are variables that receive values passed to the function when it is called (arguments). Functions may return a value using the return statement; without return, they implicitly return None. Well-designed functions do one thing well, have descriptive names, and are short enough to understand at a glance.</p><p>Python functions support several parameter types. Positional parameters are matched by position: def greet(name, greeting) must be called as greet("Alice", "Hello"). Default parameters have fallback values: def greet(name, greeting="Hello") allows calling as greet("Alice"). Keyword arguments allow calling in any order: greet(greeting="Hi", name="Bob"). *args collects extra positional arguments as a tuple; **kwargs collects extra keyword arguments as a dictionary. These features make Python functions highly flexible.</p><p>Variable scope determines where a variable is accessible. Variables defined inside a function are local—they exist only during the function call and are invisible outside. Variables defined at the module level are global. The global keyword (used sparingly) allows a function to modify a global variable. Enclosing scope in nested functions is accessed via the nonlocal keyword. Understanding scope prevents bugs caused by accidentally modifying variables in unintended places—a common source of errors in large programs.</p><p>Modules are Python files containing reusable code that you can import. Python's standard library includes modules for math, operating system interaction (os), regular expressions (re), date and time (datetime), random numbers (random), and much more. Import with import math and use as math.sqrt(16). Or import specific functions: from math import sqrt, pi. Install third-party packages with pip install package_name and import them the same way. Breaking your own code into modules—one file per logical component—improves organization, readability, and reusability, which are hallmarks of professional Python development.</p>` },
      { title: 'Data Structures: Lists, Dicts, and Sets', duration: 20, order: 5, content: `<h3>Organizing Data Efficiently</h3><p>Python's built-in data structures are among the language's most powerful features. A list is an ordered, mutable sequence of any data types: fruits = ["apple", "banana", "cherry"]. Lists support indexing (fruits[0] = "apple"), slicing (fruits[1:3] = ["banana","cherry"]), and many methods: append(), insert(), remove(), pop(), sort(), reverse(), and len(). Lists are the most versatile data structure—use them when you need an ordered collection that may change. Nested lists (lists within lists) create 2D structures useful for matrices and grids.</p><p>A dictionary (dict) stores key-value pairs: student = {"name": "Alice", "grade": 90, "age": 20}. Access values by key: student["name"] returns "Alice". Add or update: student["email"] = "alice@example.com". Check existence: "grade" in student returns True. Iterate: for key, value in student.items(). Dictionaries provide O(1) average-case lookup by key, making them ideal for representing records, counting occurrences, and mapping relationships. Dictionary comprehensions create dictionaries concisely: {k: v*2 for k, v in prices.items()}.</p><p>A tuple is an immutable ordered sequence: coordinates = (3.5, -2.1). Tuples are faster than lists and signal that the data should not change. They are used for fixed collections like coordinates, RGB colors, or database records. Tuple unpacking allows elegant multiple assignment: x, y = coordinates. A set is an unordered collection of unique elements: unique_tags = {"python", "code", "programming"}. Sets support fast membership testing, and mathematical set operations: union (|), intersection (&), difference (-), and symmetric difference (^). Use sets to eliminate duplicates or test membership efficiently.</p><p>Choosing the right data structure dramatically affects code clarity and performance. Use lists for ordered, mutable sequences; tuples for ordered, immutable sequences; dicts for key-based lookup; sets for unique collections and set operations. In data science and machine learning, you will encounter NumPy arrays (for numerical computation) and pandas DataFrames (for tabular data)—both built on these fundamental Python structures. A solid understanding of Python's built-in data structures is essential before graduating to these more specialized tools, and the patterns you learn here—iteration, comprehension, membership testing—will transfer directly.</p>` },
    ],
    quizzes: [
      {
        title: 'Python Programming Fundamentals - Assessment Quiz 1',
        lesson: null,
        passingScore: 70,
        questions: [
          { questionText: 'Which function is used to display output in Python?', options: [{ text: 'display()' }, { text: 'echo()' }, { text: 'print()', isCorrect: true }, { text: 'output()' }], explanation: 'The print() function outputs text to the console in Python.' },
          { questionText: 'What is the result of 7 // 2 in Python?', options: [{ text: '3.5' }, { text: '3', isCorrect: true }, { text: '4' }, { text: '1' }], explanation: '// is the integer (floor) division operator. 7 // 2 = 3 (remainder discarded).' },
          { questionText: 'Which of the following is a valid Python variable name?', options: [{ text: '2names' }, { text: 'my-name' }, { text: 'my_name', isCorrect: true }, { text: 'class' }], explanation: 'my_name is valid—starts with a letter, uses only letters/digits/underscores, and is not a keyword.' },
          { questionText: 'What does len(["a", "b", "c"]) return?', options: [{ text: '2' }, { text: '3', isCorrect: true }, { text: '4' }, { text: '0' }], explanation: 'len() returns the number of items in the list. The list has 3 elements, so len() returns 3.' },
          { questionText: 'To import the math module and use sqrt, which is correct?', options: [{ text: 'import math; math.sqrt(9)', isCorrect: true }, { text: 'import sqrt from math; sqrt(9)' }, { text: 'use math; sqrt(9)' }, { text: 'include math; math.sqrt(9)' }], explanation: 'Use "import math" then access with "math.sqrt(9)", or "from math import sqrt" then just "sqrt(9)".' },
        ],
      },
      {
        title: 'Python Programming Fundamentals - Lesson 3 Quiz',
        lessonIndex: 2,
        passingScore: 70,
        questions: [
          { questionText: 'What does the range(1, 6) function generate?', options: [{ text: '1, 2, 3, 4, 5, 6' }, { text: '1, 2, 3, 4, 5', isCorrect: true }, { text: '0, 1, 2, 3, 4, 5' }, { text: '1, 6' }], explanation: 'range(1, 6) generates integers from 1 up to (but not including) 6: 1, 2, 3, 4, 5.' },
          { questionText: 'Which keyword immediately exits a loop?', options: [{ text: 'continue' }, { text: 'return' }, { text: 'break', isCorrect: true }, { text: 'exit' }], explanation: 'The break statement immediately terminates the innermost loop.' },
          { questionText: 'What is the output of: for i in range(3): print(i)', options: [{ text: '1 2 3' }, { text: '0 1 2', isCorrect: true }, { text: '0 1 2 3' }, { text: '1 2' }], explanation: 'range(3) generates 0, 1, 2. The loop prints each on a separate line.' },
          { questionText: 'A while loop continues executing as long as its condition is:', options: [{ text: 'False' }, { text: 'True', isCorrect: true }, { text: 'None' }, { text: 'Zero' }], explanation: 'A while loop repeats its body as long as the condition evaluates to True.' },
          { questionText: 'What does "continue" do inside a loop?', options: [{ text: 'Exits the loop' }, { text: 'Repeats the loop from the start' }, { text: 'Skips the rest of the current iteration', isCorrect: true }, { text: 'Pauses the loop' }], explanation: 'continue skips the remaining code in the current iteration and moves to the next iteration.' },
        ],
      },
    ],
  },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('Connected to MongoDB')

    await Promise.all([
      User.deleteMany({}),
      Course.deleteMany({}),
      Lesson.deleteMany({}),
      Quiz.deleteMany({}),
      Enrollment.deleteMany({}),
      Progress.deleteMany({}),
    ])
    console.log('Cleared existing data')

    const hashedAdmin = await bcrypt.hash('Admin@1234', SALT_ROUNDS)
    const hashedTeacher = await bcrypt.hash('Teacher@1234', SALT_ROUNDS)
    const hashedStudent = await bcrypt.hash('Student@1234', SALT_ROUNDS)

    const studentNames = ['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten']

    const users = await User.insertMany([
      { name: 'Admin User', email: 'admin@khan.com', password: hashedAdmin, role: 'admin' },
      { name: 'Dr. Sarah Johnson', email: 'teacher1@khan.com', password: hashedTeacher, role: 'teacher', bio: 'Mathematics educator with 15 years of experience in secondary and higher education.' },
      { name: 'Prof. Michael Chen', email: 'teacher2@khan.com', password: hashedTeacher, role: 'teacher', bio: 'Physics and Biology professor passionate about making science accessible to all students.' },
      { name: 'Ms. Emily Rodriguez', email: 'teacher3@khan.com', password: hashedTeacher, role: 'teacher', bio: 'Experienced educator in History and Computer Science with a talent for storytelling.' },
      ...studentNames.map((n, i) => ({ name: `Student ${n}`, email: `student${i + 1}@khan.com`, password: hashedStudent, role: 'student' })),
    ])

    const [admin, teacher1, teacher2, teacher3, ...students] = users
    console.log(`Created ${users.length} users`)

    const teachers = [teacher1, teacher1, teacher2, teacher2, teacher3, teacher3]
    const createdCourses = []

    for (let ci = 0; ci < courseData.length; ci++) {
      const cd = courseData[ci]
      const course = await Course.create({
        title: cd.title,
        slug: makeSlug(cd.title),
        description: cd.description,
        category: cd.category,
        level: cd.level,
        thumbnail: `https://picsum.photos/seed/${ci + 1}/800/450`,
        tags: cd.tags,
        teacher: teachers[ci]._id,
        status: 'approved',
        totalDuration: cd.lessons.reduce((sum, l) => sum + l.duration, 0),
      })

      const lessons = await Promise.all(
        cd.lessons.map((l) =>
          Lesson.create({
            course: course._id,
            title: l.title,
            content: l.content,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            order: l.order,
            duration: l.duration,
            isPublished: true,
          })
        )
      )

      const quizzes = await Promise.all(
        cd.quizzes.map((qd) =>
          Quiz.create({
            course: course._id,
            lesson: qd.lessonIndex !== undefined ? lessons[qd.lessonIndex]._id : null,
            title: qd.title,
            passingScore: qd.passingScore,
            timeLimit: 0,
            questions: qd.questions.map((q) => ({
              id: randomUUID(),
              questionText: q.questionText,
              explanation: q.explanation,
              options: q.options.map((o) => ({
                id: randomUUID(),
                text: o.text,
                isCorrect: o.isCorrect || false,
              })),
            })),
          })
        )
      )

      createdCourses.push({ course, lessons, quizzes })
      console.log(`Created course: ${course.title}`)
    }

    // students 1-5 (index 0-4) enroll in courses 1,3,6 (index 0,2,5)
    // students 6-10 (index 5-9) enroll in courses 2,4,5 (index 1,3,4)
    const enrollmentPlan = [
      { studentIndices: [0, 1, 2, 3, 4], courseIndices: [0, 2, 5] },
      { studentIndices: [5, 6, 7, 8, 9], courseIndices: [1, 3, 4] },
    ]

    for (const plan of enrollmentPlan) {
      for (const si of plan.studentIndices) {
        for (const ci of plan.courseIndices) {
          const student = students[si]
          const { course, lessons, quizzes } = createdCourses[ci]

          await Enrollment.create({ student: student._id, course: course._id, status: 'active' })

          const completedLessons = pickRandom(lessons, 2, 4).map((l) => l._id)
          const percentComplete = Math.round((completedLessons.length / lessons.length) * 100)

          const quizAttempts = quizzes.slice(0, randomInt(1, 2)).map((quiz) => {
            const score = randomInt(50, 100)
            return {
              quiz: quiz._id,
              score,
              passed: score >= quiz.passingScore,
              answers: quiz.questions.map((q) => {
                const correctOpt = q.options.find((o) => o.isCorrect)
                const useCorrect = Math.random() > 0.3
                const selectedOpt = useCorrect ? correctOpt : q.options.find((o) => !o.isCorrect) || correctOpt
                return { questionId: q.id, selectedOptionId: selectedOpt?.id || '' }
              }),
              attemptedAt: new Date(Date.now() - randomInt(1, 30) * 24 * 60 * 60 * 1000),
            }
          })

          await Progress.create({
            student: student._id,
            course: course._id,
            completedLessons,
            quizAttempts,
            lastAccessedLesson: completedLessons[completedLessons.length - 1] || null,
            percentComplete,
          })
        }
      }
    }

    console.log('Created enrollments and progress records')
    console.log('\n✅ Seed completed successfully!')
    console.log('\n--- Test Credentials ---')
    console.log('Admin:    admin@khan.com    / Admin@1234')
    console.log('Teacher1: teacher1@khan.com / Teacher@1234')
    console.log('Teacher2: teacher2@khan.com / Teacher@1234')
    console.log('Teacher3: teacher3@khan.com / Teacher@1234')
    console.log('Student:  student1@khan.com / Student@1234')
    process.exit(0)
  } catch (err) {
    console.error('Seed failed:', err)
    process.exit(1)
  }
}

seed()
